"""Minimal OOXML artifact builders for SourceOS Office Plane.

These helpers intentionally use only Python's standard library.  They create
small, deterministic-enough DOCX/XLSX/PPTX ZIP packages for guarded local
artifact generation.  They are not a replacement for LibreOffice, Collabora,
ONLYOFFICE, or a full template engine; they are the safe local bootstrap path
for simple agent-authored workroom artifacts.
"""

from __future__ import annotations

from html import escape
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile


OOXML_GENERATION_FORMATS = {"docx", "xlsx", "pptx"}


def _xml(text: str) -> str:
    return escape(text, quote=True)


def _write_zip(path: Path, files: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(path, "w", ZIP_DEFLATED) as zf:
        for name in sorted(files):
            zf.writestr(name, files[name])


def write_ooxml_artifact(
    *,
    fmt: str,
    path: Path,
    title: str,
    workroom_id: str,
    artifact_id: str,
) -> None:
    """Write a minimal OOXML artifact to path.

    Args:
        fmt: one of docx, xlsx, pptx.
        path: output path.
        title: human-readable artifact title.
        workroom_id: Professional Workroom id.
        artifact_id: OfficeArtifact id.
    """
    if fmt == "docx":
        _write_docx(path=path, title=title, workroom_id=workroom_id, artifact_id=artifact_id)
        return
    if fmt == "xlsx":
        _write_xlsx(path=path, title=title, workroom_id=workroom_id, artifact_id=artifact_id)
        return
    if fmt == "pptx":
        _write_pptx(path=path, title=title, workroom_id=workroom_id, artifact_id=artifact_id)
        return
    raise ValueError(f"unsupported OOXML generation format: {fmt}")


def _write_docx(*, path: Path, title: str, workroom_id: str, artifact_id: str) -> None:
    document = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p><w:r><w:t>{_xml(title)}</w:t></w:r></w:p>
    <w:p><w:r><w:t>Generated by SourceOS Office Plane guarded OOXML generation.</w:t></w:r></w:p>
    <w:p><w:r><w:t>Workroom: {_xml(workroom_id)}</w:t></w:r></w:p>
    <w:p><w:r><w:t>Artifact: {_xml(artifact_id)}</w:t></w:r></w:p>
    <w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>
  </w:body>
</w:document>
'''
    files = {
        "[Content_Types].xml": '''<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>
''',
        "_rels/.rels": '''<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>
''',
        "word/document.xml": document,
    }
    _write_zip(path, files)


def _write_xlsx(*, path: Path, title: str, workroom_id: str, artifact_id: str) -> None:
    rows = [
        ("Title", title),
        ("Generated By", "SourceOS Office Plane guarded OOXML generation"),
        ("Workroom", workroom_id),
        ("Artifact", artifact_id),
    ]
    row_xml = []
    for idx, (key, value) in enumerate(rows, start=1):
        row_xml.append(
            f'''<row r="{idx}"><c r="A{idx}" t="inlineStr"><is><t>{_xml(key)}</t></is></c><c r="B{idx}" t="inlineStr"><is><t>{_xml(value)}</t></is></c></row>'''
        )
    sheet = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetData>
    {''.join(row_xml)}
  </sheetData>
</worksheet>
'''
    files = {
        "[Content_Types].xml": '''<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
</Types>
''',
        "_rels/.rels": '''<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>
''',
        "xl/workbook.xml": '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets><sheet name="SourceOS" sheetId="1" r:id="rId1"/></sheets>
</workbook>
''',
        "xl/_rels/workbook.xml.rels": '''<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>
''',
        "xl/worksheets/sheet1.xml": sheet,
    }
    _write_zip(path, files)


def _write_pptx(*, path: Path, title: str, workroom_id: str, artifact_id: str) -> None:
    slide = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
      <p:sp>
        <p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="914400" y="914400"/><a:ext cx="7315200" cy="914400"/></a:xfrm></p:spPr>
        <p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>{_xml(title)}</a:t></a:r></a:p></p:txBody>
      </p:sp>
      <p:sp>
        <p:nvSpPr><p:cNvPr id="3" name="Body"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="914400" y="2133600"/><a:ext cx="7315200" cy="2743200"/></a:xfrm></p:spPr>
        <p:txBody><a:bodyPr/><a:lstStyle/>
          <a:p><a:r><a:t>Generated by SourceOS Office Plane guarded OOXML generation.</a:t></a:r></a:p>
          <a:p><a:r><a:t>Workroom: {_xml(workroom_id)}</a:t></a:r></a:p>
          <a:p><a:r><a:t>Artifact: {_xml(artifact_id)}</a:t></a:r></a:p>
        </p:txBody>
      </p:sp>
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>
'''
    files = {
        "[Content_Types].xml": '''<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  <Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>
</Types>
''',
        "_rels/.rels": '''<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
</Relationships>
''',
        "ppt/presentation.xml": '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:sldIdLst><p:sldId id="256" r:id="rId1"/></p:sldIdLst>
  <p:sldSz cx="9144000" cy="6858000" type="screen4x3"/>
  <p:notesSz cx="6858000" cy="9144000"/>
</p:presentation>
''',
        "ppt/_rels/presentation.xml.rels": '''<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/>
</Relationships>
''',
        "ppt/slides/slide1.xml": slide,
    }
    _write_zip(path, files)
